### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by juanshishido** [berkeley-stat159/project-eta#10]
Add project information to `README.md`.

@yuanyiwu do you want to take a shot at this? Maybe add some info on the paper itself and, if possible, what we plan to do (this may change).

**Comment by yuanyiwu** [comment]
Working on this! Sorry for the delay. @juanshishido

**Comment by juanshishido** [comment]
Thanks, @yuanyiwu. Once you have those updates on your fork, please submit a pull request. Cheers.

**Comment by juanshishido** [comment]
a83222ade1d52d7ce7ccd8bab44d1adcdaf678ed closes this.
