### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by jarrodmillman** [berkeley-stat159/project-eta#31]
The initial description of the project, paper, and goals was not particularly
clear.

The main goal appears to be to reproduce results from the paper - identified
specific results to attempt to replicate (image from paper), but you didn't
present any preliminary analysis towards that aim.

Identified struggles with applying preprocessing and linear modelling concepts
from class to their data.  This is a good first step and effort should be
redoubled to accomplish this ASAP.

Seemed to have a good grasp of their overall goal, but no specific, short-term,
managable goals toward that end. You need to complete the regression analysis
to better understand the data and the challenges of reaching their goal to
reproduce the paper's results.

You appear to be using `statsmodels`, but haven't mentioned it as a dependency.
In order for me to be able to run your code, you need to explicitly mention
dependencies as discussed during lecture 18.

You still have a lot of work to do, but there is still time.

**Comment by jarrodmillman** [comment]
I am worried about your teams progress.  It appears that you haven't done anything since last week.  Time is running short and you still have a lot of work to do.  If you have run into a major problem, please let me know immediately.  

It appears that you've only added one code file so far:
https://github.com/berkeley-stat159/project-eta/blob/master/code/logistic%20regression.py

And it is essentially one or two lines of code.  If you don't start working on your project soon, I am concerned that you will have nothing to turn in for your project.  Remember the project is 55% of your grade.

Please review the grading criteria:
http://www.jarrodmillman.com/rcsds/notes/rubric.pdf

As well as my comments from lecture 22:
http://www.jarrodmillman.com/rcsds/lectures/day22.html

**Comment by juanshishido** [comment]
Thanks for the feedback and reminder, @jarrodmillman. We have been working on a few things, but have not pushed any changes to our own forks. Still, we understand we have a lot to do. All of us are making this a priority.

Again, thanks for the concern. We are taking it seriously.
